- name: Remove host configurations
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/rhel_lab_vars.yml

  tasks:
    - name: Remove kickstarts directory
      block:
        - name: Remove kickstarts directory
          ansible.builtin.file:
            path: /var/lib/libvirt/kickstarts
            state: absent

    - name: Remove host config
      block:
        - name: Remove headless servers from hosts file
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: ^{{ item.ip }}|\s{{ item.hostname }}
            state: absent
          loop: "{{ headless_servers }}"

        - name: Remove graphical workstations from hosts file
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: ^{{ item.ip }}|\s{{ item.hostname }}
            state: absent
          loop: "{{ graphical_workstations }}"

        - name: Remove rhel lab public key
          ansible.builtin.file:
            dest: "/home/{{ user_name }}/.ssh/lab_rsa.pub"
            state: absent

        - name: Remove rhel lab key
          ansible.builtin.file:
            dest: "/home/{{ user_name }}/.ssh/lab_rsa"
            state: absent

        - name: Remove SSH config for headless servers
          ansible.builtin.blockinfile:
            path: /home/{{ user_name }}/.ssh/config
            state: absent
            marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RHEL LAB - {{ item.hostname }}"
          loop: "{{ headless_servers }}"

        - name: Remove SSH config for root access to headless servers
          ansible.builtin.blockinfile:
            path: /home/{{ user_name }}/.ssh/config
            state: absent
            marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RHEL LAB - {{ item.hostname }} - root access"
          loop: "{{ headless_servers }}"

        - name: Remove SSH config for graphical workstations
          ansible.builtin.blockinfile:
            path: /home/{{ user_name }}/.ssh/config
            state: absent
            marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RHEL LAB - {{ item.hostname }}"
          loop: "{{ graphical_workstations }}"

        - name: Remove SSH config for root access to graphical workstations
          ansible.builtin.blockinfile:
            path: /home/{{ user_name }}/.ssh/config
            state: absent
            marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RHEL LAB - {{ item.hostname }} - root access"
          loop: "{{ headless_servers }}"

