---
- name: Install common packages
  ansible.builtin.dnf:
    name:
      - sshpass
      - vim
      - bash-completion
      - man-pages
      - man-db
    state: present

- name: Configure root account
  block:
    - name: Set root password
      ansible.builtin.user:
        name: root
        password: "{{ 'redhat' | password_hash('sha512') }}"

    - name: Create .ssh directory for root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy lab SSH keys for root
      ansible.builtin.copy:
        remote_src: yes
        src: "/tmp/{{ item }}"
        dest: "/root/.ssh/{{ item }}"
        owner: root
        group: root
        mode: '0600'
      loop:
        - lab_rsa
        - lab_rsa.pub

    - name: Ensure authorized_keys for root contains lab key
      ansible.posix.authorized_key:
        user: root
        key: "{{ lookup('file', '/tmp/lab_rsa.pub') }}"
        state: present

- name: Configure SSH daemon
  block:
    - name: Allow root login and password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?{{ item.key }}'
        line: '{{ item.key }} {{ item.value }}'
        state: present
      loop:
        - { key: 'PermitRootLogin', value: 'yes' }
        - { key: 'PasswordAuthentication', value: 'yes' }
      notify: Restart sshd

- name: Flush handlers to restart sshd if needed
  meta: flush_handlers

- name: Configure student account
  block:
    - name: Create 'student' user
      ansible.builtin.user:
        name: student
        comment: "Student"
        groups: wheel
        state: present
        password: "{{ 'student' | password_hash('sha512') }}"

    - name: Create .ssh directory for student
      ansible.builtin.file:
        path: /home/student/.ssh
        state: directory
        owner: student
        group: student
        mode: '0700'

    - name: Copy lab SSH keys for student
      ansible.builtin.copy:
        remote_src: yes
        src: "/tmp/{{ item }}"
        dest: "/home/student/.ssh/{{ item }}"
        owner: student
        group: student
        mode: '0600'
      loop:
        - lab_rsa
        - lab_rsa.pub

    - name: Ensure authorized_keys for student contains lab key
      ansible.posix.authorized_key:
        user: student
        key: "{{ lookup('file', '/tmp/lab_rsa.pub') }}"
        state: present

    - name: Ensure correct ownership of student .ssh directory
      ansible.builtin.file:
        path: /home/student/.ssh
        owner: student
        group: student
        recurse: yes

- name: Configure passwordless sudo for student
  ansible.builtin.copy:
    dest: /etc/sudoers.d/student
    content: "student ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -csf %s
    owner: root
    group: root
    mode: '0440'

- name: Disable SSH host key checking in the lab environment
  ansible.builtin.copy:
    dest: /etc/ssh/ssh_config.d/01-training.conf
    content: |
      Host *
          StrictHostKeyChecking no
          ServerAliveInterval 100
    owner: root
    group: root
    mode: '0644'

- name: Configure /etc/hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ etc_hosts_entries }}"
    marker: "# ANSIBLE MANAGED BLOCK FOR RHEL LAB"
  when: etc_hosts_entries is defined and etc_hosts_entries != ""
