---
- name: Ensure @virtualization group is installed
  ansible.builtin.package:
    name: "@virtualization"
    state: present

- name: Ensure libvirt_users are in the libvirt group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: libvirt
    append: true
  loop: "{{ libvirt_users }}"

- name: Create directory for ISOs
  ansible.builtin.file:
    path: /var/lib/libvirt/isos
    state: directory
    owner: root
    group: wheel
    mode: "0775"

- name: Ensure community.libvirt prerequisites are installed
  ansible.builtin.package:
    name:
      - python3-libvirt
      - python3-lxml
    state: present
