---
- name: Ensure @virtualization group is installed
  ansible.builtin.package:
    name: "@virtualization"
    state: present

- name: Ensure libvirt_users are in the libvirt group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    append: true

- name: Ensure community.libvirt prerequisites are installed
  ansible.builtin.package:
    name:
      - python3-libvirt
      - python3-lxml
    state: present

