---
- hosts: all
  become: yes

  tasks:
    - name: Include common tasks
      include_tasks: tasks/01-common.yml

    - name: Include graphical system tasks
      include_tasks: tasks/02-graphical.yml
      when: system_type == "graphical"

    - name: Include headless system tasks
      include_tasks: tasks/03-headless.yml
      when: system_type == "headless"

    - name: Include Red Hat Academy lab tasks
      include_tasks: tasks/04-rha_labs.yml
      when: hostname == "workstation" and rha_labs_file_exists

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: Set graphical default target
      ansible.builtin.command: systemctl set-default graphical.target
